build: squash: move arg descriptions to template comments & echo more help

diff --git a/.github/actions/shellcheck/action.yml b/.github/actions/shellcheck/action.yml
--- a/.github/actions/shellcheck/action.yml
+++ b/.github/actions/shellcheck/action.yml
@@ -6,23 +6,19 @@
 
 name: ShellCheck
 
+# For details on each of these input arguments, see:
+#   ../../../workflow-templates/shellcheck.yml
+# which invokes this action.
 inputs:
 
   root-dirs:
-    description: "Directories to search for .sh files, space-separated."
     reqired: true
 
-  # We pin a reasonable default version here and will update it over time.
-  # However, repositories that are particuarly concerned about
-  # build stability should specify an override shellcheck-version
-  # and manage updates themselves.
   shellcheck-version:
-    description: "ShellCheck version to install.Must be a tag or branch of https://github.com/koalaman/shellcheck."
     required: false
     default: "v0.9.0"
 
   shellcheck-options:
-    description: "Command-line options to pass through to shellcheck."
     required: false
     default: ""
 
@@ -38,7 +34,7 @@ runs:
     - shell: bash
       run: |
         # Download, unpack & install ShellCheck ${{ inputs.shellcheck-version }}.
-        wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${{ inputs.shellcheck-version }}/shellcheck-${{ inputs.shellcheck-version}}.linux.x86_64.tar.xz" | tar -xJ
+        wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${{ inputs.shellcheck-version }}/shellcheck-${{ inputs.shellcheck-version }}.linux.x86_64.tar.xz" | tar -xJ
         sudo cp "shellcheck-${{ inputs.shellcheck-version }}/shellcheck" /usr/bin
         echo "Successfully installed:"
         shellcheck -V
@@ -46,12 +42,19 @@ runs:
 
     - shell: bash
       run: |
-        # Ensure that at least one shell script will be checked
+        # Ensure that at least one shell script will be checked & print helpful info
         if [[ -z "$(find ${{ inputs.root-dirs }} -name '*.sh')" ]] ; then
-          echo "::error::Error: No .sh files found within any of the root-dirs: ${{ inputs.root-dirs }}" && exit 1
+          echo "::error::Error: No .sh files found within any of the root-dirs: ${{ inputs.root-dirs }}"
+          exit 1
         fi 
         echo "The following shell scripts will be checked:"
         find ${{ inputs.root-dirs }} -name '*.sh'
+        echo
+        echo "If ShellCheck passes, the next step will have no output."
+        echo "If ShellCheck fails, you should see a list of violations."
+        echo "Each violation type has an SCXXXX code which can be looked up at https://www.shellcheck.net/wiki/SCXXXX"
+        echo "We recommend that you try to resolve any violations."
+        echo "In the case where resolving the violation doesn't make sense, you can use directives (https://www.shellcheck.net/wiki/Directive) to ignore a single violation instance or an entire shell script."
         echo
 
     # This step is intentionally a big one-line command so that
